name: Deploy Vite React App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Inject environment variables from secrets
      - name: Configure environment variables
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
